import { appendFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { isAbsolute, join } from 'node:path';
import type { Config } from '../config/schema.js';

export interface MemoryPaths {
  dir: string;
  /** contexte permanent (écrit par l'humain, jamais écrasé) */
  context: string;
  /** état courant (régénéré à la fin de chaque tâche) */
  state: string;
  architecture: string;
  decisions: string;
  /** échecs précédents (ajouts seulement) */
  failures: string;
  /** index des tâches (régénéré) */
  tasks: string;
  tasksDir: string;
  sessionsDir: string;
  runsDir: string;
  gitignore: string;
}

export function memoryPaths(cwd: string, cfg: Pick<Config, 'memory'>): MemoryPaths {
  const dir = isAbsolute(cfg.memory.dir) ? cfg.memory.dir : join(cwd, cfg.memory.dir);
  return {
    dir,
    context: join(dir, 'context.md'),
    state: join(dir, 'state.md'),
    architecture: join(dir, 'architecture.md'),
    decisions: join(dir, 'decisions.md'),
    failures: join(dir, 'failures.md'),
    tasks: join(dir, 'tasks.md'),
    tasksDir: join(dir, 'tasks'),
    sessionsDir: join(dir, 'sessions'),
    runsDir: join(dir, 'runs'),
    gitignore: join(dir, '.gitignore'),
  };
}

const PLACEHOLDER = (hint: string) => `_${hint}_\n`;

const TEMPLATES: Record<'context' | 'architecture' | 'decisions', string> = {
  context:
    '# Project context\n\n' +
    '<!-- Permanent context, written by you. CodeBreak reads it selectively and never overwrites it. -->\n\n' +
    '## Goal\n' + PLACEHOLDER('What this project is for, in a few lines.') + '\n' +
    '## Constraints\n' + PLACEHOLDER('Rules every agent must follow: style, forbidden changes, tooling.') + '\n' +
    '## Commands\n' + PLACEHOLDER('How to build, test and lint.'),
  architecture:
    '# Architecture\n\n' +
    '<!-- Structure of the code base. One "## Section" per area; CodeBreak picks the sections relevant to a task. -->\n\n' +
    '## Overview\n' + PLACEHOLDER('Main modules and how they fit together.'),
  decisions:
    '# Decisions\n\n' +
    '<!-- One "## YYYY-MM-DD · title" per decision, with the reason. Add "tags:" or "files:" lines to help selection. -->\n',
};

const GITIGNORE =
  '# Volatile files written by CodeBreak. context.md, architecture.md and decisions.md are meant to be committed.\n' +
  'state.md\nfailures.md\ntasks.md\ntasks/\nsessions/\nruns/\n';

const HEADERS = {
  failures: '# Failures\n\n<!-- Appended by CodeBreak after each failed attempt (secrets redacted). Delete entries that are no longer relevant. -->\n',
  tasks: '# Tasks\n\n<!-- Index regenerated by CodeBreak; the manifests live in tasks/. -->\n',
  state: '# Current state\n',
};

/** Crée `.codebreak/` et ses fichiers s'ils n'existent pas. Ne touche jamais un fichier existant. `null` si désactivé/impossible. */
export function ensureMemory(cwd: string, cfg: Pick<Config, 'memory'>): MemoryPaths | null {
  if (!cfg.memory.enabled) return null;
  const p = memoryPaths(cwd, cfg);
  try {
    if (!existsSync(p.dir) && !cfg.memory.auto_init) return null;
    for (const d of [p.dir, p.tasksDir, p.sessionsDir, p.runsDir]) mkdirSync(d, { recursive: true });
    const seed = (path: string, content: string) => existsSync(path) || writeFileSync(path, content, 'utf8');
    seed(p.context, TEMPLATES.context);
    seed(p.architecture, TEMPLATES.architecture);
    seed(p.decisions, TEMPLATES.decisions);
    seed(p.failures, HEADERS.failures);
    seed(p.tasks, HEADERS.tasks);
    seed(p.state, HEADERS.state);
    seed(p.gitignore, GITIGNORE);
    return p;
  } catch {
    return null;
  }
}

export function appendFile(path: string, text: string): void {
  appendFileSync(path, text, 'utf8');
}
